package fr.keyser.evolution.model;

public enum Trait {
	COOPERATION, FAT_TISSUE, FORAGING, SCAVENGER, HORNS, QUILLS, VENOM, FERTILE, LONGNECK, CARNIVOROUS, INTELLIGENT, AMBUSH, BURROWING, CLIMBING, HARD_SHELL, DEFENSIVE_HERDING, SYMBIOSIS, WARNING_CALL, PACK_HUNTING, PEST
}
